version: "2"
services:
  chatserver:
    image: deu-door/chat-server
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: doorchat
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      KAFKA_HOST: kafka:9092
      KAFKA_GROUP_ID: deu-door-chat-server

  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: doorchat
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin